pipeline:
    name: pipeline-template
    identifier: pipelinetemplate
    tags: {}
    projectIdentifier: New_Git_Exp
    orgIdentifier: NandeeshTest
    stages:
        - stage:
              name: artifact
              identifier: artifact
              template:
                  templateRef: org.K8sHelmChartZManifest
                  versionLabel: Artifact
                  templateInputs:
                      type: Deployment
                      spec:
                          serviceConfig:
                              serviceRef: <+input>
                              serviceDefinition:
                                  type: Kubernetes
                                  spec:
                                      artifacts:
                                          primary:
                                              type: DockerRegistry
                                              spec:
                                                  imagePath: <+input>
                                                  tag: <+input>
                          infrastructure:
                              environmentRef: <+input>
