pipeline:
  name: parent
  identifier: parent
  projectIdentifier: CDUsecases
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: child
        identifier: child
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: childp
          project: CDUsecases
          inputs:
            identifier: childp
            template:
              templateInputs:
                stages:
                  - stage:
                      identifier: cd
                      template:
                        templateInputs:
                          type: Deployment
                          spec:
                            environment:
                              environmentRef: <+input>
                              environmentInputs: <+input>
                              serviceOverrideInputs: <+input>
                              infrastructureDefinitions: <+input>
    - stage:
        name: test
        identifier: test
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "Hi"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
